# Generated by Django 4.2.1 on 2023-06-01 14:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevator_number', models.IntegerField(unique=True)),
                ('current_floor', models.IntegerField(default=0)),
                ('destination_floor', models.IntegerField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('is_door_open', models.BooleanField(default=False)),
                ('is_working', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevators', models.ManyToManyField(to='elevator.elevator')),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('requested_floor', models.PositiveIntegerField()),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.elevator')),
            ],
        ),
    ]
